/**
 * 构建时脚本：读取 server/skills/xuan/ 下的 SKILL.md + references/*.md
 * 输出 server-workers/services/skill-content.ts（两个 export 常量）
 *
 * 截断规则与 server/bazi-ai.cjs 中的 loadSkillContent() 一致：
 *   - SKILL.md 截断为 12000 字符
 *   - 每个 reference 文件截断为 8000 字符
 *   - referencesContent 总截断为 15000 字符
 */
import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const XUAN_DIR = path.join(__dirname, '..', 'server', 'skills', 'xuan');
const REFS_DIR = path.join(XUAN_DIR, 'references');
const OUTPUT_FILE = path.join(__dirname, '..', 'server-workers', 'services', 'skill-content.ts');

function main() {
  let skillContent = '';
  let referencesContent = '';

  // 加载 SKILL.md
  const skillPath = path.join(XUAN_DIR, 'SKILL.md');
  if (fs.existsSync(skillPath)) {
    const raw = fs.readFileSync(skillPath, 'utf-8');
    skillContent = raw.substring(0, 12000);
    console.log(`[bundle-xuan-skill] SKILL.md: ${raw.length} chars → truncated to ${skillContent.length}`);
  } else {
    console.warn('[bundle-xuan-skill] SKILL.md not found, using empty string');
  }

  // 加载 references/*.md
  if (fs.existsSync(REFS_DIR)) {
    const files = fs.readdirSync(REFS_DIR).filter(f => f.endsWith('.md')).sort();
    const parts: string[] = [];
    for (const file of files) {
      const filePath = path.join(REFS_DIR, file);
      try {
        const content = fs.readFileSync(filePath, 'utf-8');
        const truncated = content.length > 8000
          ? content.substring(0, 8000) + '\n...[已截断]'
          : content;
        parts.push(`=== ${file} ===\n${truncated}`);
        console.log(`[bundle-xuan-skill] references/${file}: ${content.length} chars`);
      } catch (e: unknown) {
        console.warn(`[bundle-xuan-skill] Failed to read ${file}: ${(e as Error).message}`);
      }
    }
    referencesContent = parts.join('\n\n').substring(0, 15000);
    console.log(`[bundle-xuan-skill] ${files.length} reference files → total ${referencesContent.length} chars`);
  } else {
    console.warn('[bundle-xuan-skill] references/ directory not found');
  }

  // 输出 TypeScript 文件
  const output = `// Auto-generated by scripts/bundle-xuan-skill.ts — DO NOT EDIT
export const SKILL_CONTENT = ${JSON.stringify(skillContent)};

export const REFERENCES_CONTENT = ${JSON.stringify(referencesContent)};
`;

  fs.writeFileSync(OUTPUT_FILE, output, 'utf-8');
  console.log(`[bundle-xuan-skill] Output: ${OUTPUT_FILE}`);
}

main();
